# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy to Github Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - master
jobs:
  # Build job
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
              node-version: '12'
      - name: Install packages
        run: npm i
      - name: Set Creds
        run: git config user.name "Harpreet Singh" && git config user.email "harpreetsinghmunday94@gmail.com"
      - name: Deploy
        run: npm run deploy
